// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiidfrzonwowbzggltft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaWRmcnpvbndvd2J6Z2dsdGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTk4NzAsImV4cCI6MjA2OTI5NTg3MH0.9tyiu8uAamQqMjX5xLGpIsa7qm_Ux3QyF4qLcbVG4NE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});